---
- name: Create temporary download directory
  tempfile:
    state: directory
    suffix: ".vagrant_download"
  register: vagrant_download_dir
  changed_when: no

- name: Download Vagrant package
  get_url:
    url: "{{ vagrant_pkg_url }}"
    dest: "{{ vagrant_download_dir.path }}/{{ vagrant_pkg }}"
    checksum: "{{ vagrant_checksum }}"
    mode: 0644
  become: yes

- name: Install Vagrant
  apt:
    deb: "{{ vagrant_download_dir.path }}/{{ vagrant_pkg }}"
  become: yes

- name: Delete temporary download directory
  file:
    path: "{{ vagrant_download_dir.path }}"
    state: absent
  changed_when: no
